//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Car : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Single Drive
        {
            get
            {
                return SteamVR_Actions.car_Drive;
            }
        }
        
        public virtual SteamVR_Action_Boolean OutCar
        {
            get
            {
                return SteamVR_Actions.car_OutCar;
            }
        }
        
        public virtual SteamVR_Action_Single BrakeDrive
        {
            get
            {
                return SteamVR_Actions.car_BrakeDrive;
            }
        }
        
        public virtual SteamVR_Action_Boolean ForwardPeredacha
        {
            get
            {
                return SteamVR_Actions.car_ForwardPeredacha;
            }
        }
        
        public virtual SteamVR_Action_Boolean BackPeredacha
        {
            get
            {
                return SteamVR_Actions.car_BackPeredacha;
            }
        }
        
        public virtual SteamVR_Action_Boolean ExitScene
        {
            get
            {
                return SteamVR_Actions.car_ExitScene;
            }
        }
        
        public virtual SteamVR_Action_Boolean CarEngine
        {
            get
            {
                return SteamVR_Actions.car_CarEngine;
            }
        }
    }
}
